# This workflow uses the update-package-lock action to update BSI dependencies.
name: BSI Update

on:
  schedule:
    - cron: "30 12-23 * * 1-5" # Mon-Fri 8:30AM-7:30PM EDT. 7:30AM-6:30PM EST.
    - cron: "30 0-1 * * 2-6" # Mon-Fri 8:30PM-9:30PM EDT. 7:30PM-8:30PM EST.
  workflow_dispatch: # manual trigger

jobs:
  build:
    # self-hosted doesn't work for public repos (security), so need to use ubuntu
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: Brightspace/third-party-actions@actions/checkout

      - name: Use Node.js
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14.x'

      - name: Update package-lock.json
        uses: BrightspaceUI/actions/update-package-lock@master
        with:
          APPROVAL_TOKEN: ${{ secrets.BSI_AUTO_APPROVE_GITHUB_TOKEN }}
          AUTO_MERGE_TOKEN: ${{ secrets.BSI_AUTO_APPROVE_GITHUB_TOKEN }}
          BRANCH_NAME: ghworkflow/bsi_auto_update
          COMMIT_MESSAGE: 'BSI Auto Update Dependencies'
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: 'Updating BSI Dependencies'
